export const MYNFT_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_MYNFT_CONTRACT_ADDRESS || process.env.MYNFT_CONTRACT_ADDRESS || ''

export const MARKETPLACE_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_MARKETPLACE_CONTRACT_ADDRESS || process.env.MARKETPLACE_CONTRACT_ADDRESS || ''
